############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Projects"
url = "/blog"
weight = 3

[[main]]
name = "Experience"
url = "/experience"
weight = 4

[[main]]
name = "Certifications"
url = "/certifications"
weight = 5

[[main]]
name = "Competitions"
url = "/hackathons"
weight = 6


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Projects"
url = "/blog"
weight = 2

[[footer]]
name = "Competitions"
url = "/hackathons"
weight = 3

[[footer]]
name = "Experience"
url = "/experience"
weight = 4

[[footer]]
name = "Certifications"
url = "/certifications"
weight = 5

[[footer]]
name = "Contact"
url = "/contact"
weight = 6
